language: node_js
node_js:
  - "9.11.1"
sudo: required
services:
  - docker

before_install:
  - docker build -t yrios056/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run yrios056/react-test npm test -- --coverage

after_seccess:
  - docker build -t yrios056/multi-client ./client
  - docker build -t yrios056/multi-nginx ./nginx
  - docker build -t yrios056/multi-server ./server
  - docker build -t yrios056/multi-worker ./worker
# login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push yrios056/multi-client
  - docker push yrios056/multi-nginx
  - docker push yrios056/multi-server
  - docker push yrios056/multi-worker
